---
name: dci-component
description: "DCI Component"

inputs:
  # API Secrets
  dciClientId:
    description: "Remote CI client ID"
    required: true
  dciApiSecret:
    description: "Remote CI API secret"
    required: true
  # DCI Control Server (Optional)
  dciCsUrl:
    description: "Remote CI control server URL"
    required: true
    default: "https://api.distributed-ci.io/"
  # Component details (Required)
  dciTopics:
    description: "Comma separated list of DCI topics"
    required: true
  componentName:
    description: "DCI component name"
    required: true
  componentVersion:
    description: "DCI component version"
    required: true
  # Component details (Optional)
  componentRelease:
    description: "DCI component release"
    required: true
  componentTags:
    description: "Comma separated list of DCI component Tags"
    required: false
  componentUrl:
    description: "DCI component URL"
    required: false
  componentData:
    description: "DCI component data"
    required: false

outputs:
  components:
    description: "DCI components"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: box
  color: red
